### ISSUE TITLE
Constant flashing white screen in a few games

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Gameboy_MiSTer#225]
Some GBC games have a constant flashing white screen all over the menus. It's very disorienting and could induce strokes for people sensitive to this stuff. Here are the games where I've noticed this issue. There could be more:
-A Bug's Life
-Men in Black: The Series
-Robot Wars: Metal Mayhem
-Toy Story Racer (much less frequent and disorienting)

**Comment by maij** [comment]
I've played through A Bug's life and there is flashing during the intro logos and e.g. between each credits page. This is the same behaviour on the Sameboy, at least. I think it may actually just be how the game draws the the screen.

I have not tried the other games you mentioned.

**Comment by maij** [comment]
I had another thought on this. Since the original handhelds didn't have a backlight for the LCD screens, these flashes would not have been as noticeable as they are on a modern screen. I wonder if there is a way to accurately implement no-backlight screens on the MiSTer. 

I haven't checked, but these games may be turning off the display between screens, the stabilize video menu option may help in this case.

**Comment by paulb-nl** [comment]
Currently the core shows a white screen when the LCD is disabled but it appears that the GBC will repeat the last frame for a short time (1 frame?) before showing a white screen.

These games probably disable and enable the screen before the repeated frame is finished displaying.

There have been some fixes to Sameboy recently about this same issue.

**Comment by paulb-nl** [comment]
This should be fixed by 2439aa47479a960acdb7026f068e0d7bf380dcf7
