### ISSUE TITLE
Noisy sample audio in mahjong GBC games by Studio Saizensen

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/Gameboy_MiSTer#241]
First of all, huge thanks for all recent improvements in the core related to sample playback in GBC games.
I've noticed that even with the latest core (20230501) some games still have noticeable noise over played voice samples. All of those I found are, perhaps not coincidentally, from the same developer's titles.

Dejiko no Mahjong Party (Japan).gbc
Kidou Senkan Nadesico - Ruri Ruri Mahjong (Japan).gbc
Shinseiki Evangelion - Mahjong Hokan Keikaku (Japan).gbc

These three games are all licensed mahjong games developed by Studio Saizensen and published by King Records. All of them feature voice samples during gameplay. They also play samples on title screens so they can be quickly tested. Unfortunately I have no actual Game Boy hardware to test with, so my only point of reference is emulation.
I've attached two recordings from the Evangelion mahjong title screen. The first is from Sameboy v0.15.8. The second is captured from Analog IO board's optical port connected to an external DAC and normalized to have the same volume level as the first recording.

[Evangelion Sameboy.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/11375309/Evangelion.Sameboy.zip)
[Evangelion MiSTer (-12.6 db).wav.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/11375312/Evangelion.MiSTer.-12.6.db.wav.zip)

**Comment by paulb-nl** [comment]
These games seem to somehow be using the noise channel for the voices.

Kidou Senkan Nadesico sets
$FF20=$FF
$FF21=$F8
$FF22=$C7
$FF23=$BF

The game then alternates writing $88 and $00 to $FF25 to enable/disable the mixing of the noise channel.

**Comment by maij** [comment]
A couple more observations:
- The artefacts are  purely in the noise channel as expected from @paulb-nl's post (if I disable the other audio channels during the "voice sample" the noise persists, and if I disable the noise channel alone there is no audio, i.e. muted)
- Timer interrupts are used throughout the menu music, but they are disabled (IME disabled) during the "voice sample", which means that this shouldn't be related to #101.
- Modifying the DAC emulation properties in Sameboy doesn't introduce artefacts on the noise channel. So it's probably not the analogue emulation component (as well as the fact that this issue appears to have been prevalent through all the recent audio changes)

All together this suggests that the noise channel logic is wrong somewhere (and this may affect SQ1 + SQ2 if it's common logic). It shouldn't be zombie mode related since the $ff25 (NR42) is not written to during the sample.

**Comment by maij** [comment]
I've found the problem and it's actually just a bug in the noise channel implementation. This issue only crops up when you want extremely low frequency clocking of the LFSR, which most games don't appear to use. The bug is in the period counter not being wide enough for these low frequencies.

**Comment by Thelypody** [comment]
I tried the attached build, but unfortunately it did not fix the issue for me. Voice samples in these games now sound very quiet compared to music, making them almost inaudible. At least the blaring random noise is not as present.

**Comment by maij** [comment]
Sorry about that, I uploaded the wrong file! Please give the updated link a try.

**Comment by Thelypody** [comment]
The new build works great! Played a few hands in Dejiko and Evangelion mahjong games, all voice samples are clear without background noise. Thank you very much!
