### ISSUE TITLE
Missing End Level Score In Donkey Kong

### ISSUE THREAD

**Issue by wolfpacleader1986** [MiSTer-devel/Gameboy_MiSTer#34]
After you finish a level, a pop up is supposed to appear showing the levels in the current section and your clear times. This instead shows up as blank.

**Comment by wolfpacleader1986** [comment]
I have a picture showing it if I can upload it

**Comment by brNX** [comment]
sure, please post a screenshot if you can, 
can you also please check if it also happens with this version:
[Gameboy-shantae-zeldaintro.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/3030107/Gameboy-shantae-zeldaintro.zip)

**Comment by Lavos** [comment]
Here's some screenshots that show:
- missing score overlay
- flickering on the lines that appear above+below the header on the top of pause screen

Source | Score Screen | Pause Screen
--- | --- | ---
Core (MiSTer v190515, GAMEBOY v190511)  |  ![score](http://d3rtv5n06gl2t2.cloudfront.net/mister/score.png) | ![pause](http://d3rtv5n06gl2t2.cloudfront.net/mister/pause.png)
Emulator (expected behavior) | ![score](http://d3rtv5n06gl2t2.cloudfront.net/mister/score-emulator.png) | ![pause](http://d3rtv5n06gl2t2.cloudfront.net/mister/pause-emulator.png)

There was no change with the provided core.

**Comment by brNX** [comment]
thanks for the screenshots @Lavos

**Comment by paulb-nl** [comment]
Score card is fixed fd8383358b4640c5187333dd34357be5fc949198

**Comment by brNX** [comment]
this can be closed
